/* Epic ASCII Battles Core - FFI Interface */

#ifndef EPIC_ASCII_BATTLES_CORE_H
#define EPIC_ASCII_BATTLES_CORE_H

/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
namespace epic_ascii_battles {
#endif  // __cplusplus

typedef struct Battle Battle;

typedef struct EventStream EventStream;

/**
 * Opaque handle to a battle simulation
 */
typedef struct SimHandle {
  struct Battle battle;
  struct EventStream event_stream;
} SimHandle;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new battle simulation with the given seed
 * Returns an opaque pointer to the simulation handle
 *
 * # Safety
 * The returned pointer must be freed with sim_free
 */
struct SimHandle *sim_new(uint64_t seed);

/**
 * Initialize a battle with team compositions
 * team_a_json and team_b_json should be JSON arrays of combatant definitions
 *
 * # Safety
 * handle must be a valid pointer returned by sim_new
 * team_a_json and team_b_json must be valid null-terminated C strings
 */
bool sim_init_battle(struct SimHandle *handle, const char *team_a_json, const char *team_b_json);

/**
 * Advance the simulation by one tick
 *
 * # Safety
 * handle must be a valid pointer returned by sim_new
 */
void sim_tick(struct SimHandle *handle);

/**
 * Get all events since the last call to this function as a JSON string
 * Returns a pointer to a null-terminated C string that must be freed with sim_free_string
 *
 * # Safety
 * handle must be a valid pointer returned by sim_new
 */
char *sim_get_events_json(struct SimHandle *handle);

/**
 * Get the current battle state as a JSON string
 * Returns a pointer to a null-terminated C string that must be freed with sim_free_string
 *
 * # Safety
 * handle must be a valid pointer returned by sim_new
 */
char *sim_get_state_json(struct SimHandle *handle);

/**
 * Check if the battle has finished
 *
 * # Safety
 * handle must be a valid pointer returned by sim_new
 */
bool sim_is_finished(struct SimHandle *handle);

/**
 * Get the winner of the battle
 * Returns 0 for team A, 1 for team B, -1 if battle is still ongoing
 *
 * # Safety
 * handle must be a valid pointer returned by sim_new
 */
int32_t sim_get_winner(struct SimHandle *handle);

/**
 * Free a string returned by the library
 *
 * # Safety
 * s must be a pointer returned by sim_get_events_json or sim_get_state_json
 */
void sim_free_string(char *s);

/**
 * Free a simulation handle
 *
 * # Safety
 * handle must be a valid pointer returned by sim_new and not already freed
 */
void sim_free(struct SimHandle *handle);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#ifdef __cplusplus
}  // namespace epic_ascii_battles
#endif  // __cplusplus

#endif  /* EPIC_ASCII_BATTLES_CORE_H */
